server:
  port: 8080

spring:
  profiles:
    active: test  # 기본은 dev로 켜지게 설정

# 로그 설정 (SQL 및 바인딩 값까지 자세히 출력)
logging:
  level:
    root: DEBUG  # 전체 애플리케이션 로그 레벨을 DEBUG로 설정
    #    org.hibernate.SQL: DEBUG
    #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    path: /var/log/myapp
    name: application.log


#https://velog.io/@hanqjun2660/API-%EB%AC%B8%EC%84%9C%EB%A5%BC-%EB%A7%8C%EB%93%A4%EC%96%B4%EC%A3%BC%EB%8A%94-Swagger
springdoc:
  version: V.0.0.1
  swagger-ui:
    path: /swagger.html
    tags-sorter: alpha
    operations-sorter: alpha

  api-docs:
    path: /api-docs

  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8